### ISSUE TITLE
WP7 version of collada importer

### ISSUE THREAD

**Issue by azzurit** [Bunkerbewohner/ColladaXna#18]
Hello Mathias, 

I'd like to appreciate your outstanding work on XNA collada importer project in the first place.

But in the second place I'd like to ask if there is an WP7 version of this project. 
I would suppose because it's an Importer (not even processor) it should work with any type of XNA project, but I'm getting this error after trying to import dae file (following your guide posted here: https://github.com/Bunkerbewohner/ColladaXna/wiki/Quickstart):

"Building content threw NullReferenceException: Object reference not set to an instance of an object.
   at ColladaXna.Base.Import.SkeletonImporter.GetNodeName(XmlNode xmlNode)
   at ColladaXna.Base.Import.SkeletonImporter.ReadJoints(Joint parent, IEnumerable`1 xmlNodes, ColladaModel model)
   at ColladaXna.Base.Import.SkeletonImporter.Import(XmlNode xmlRoot, ColladaModel model)
   at ColladaXna.Base.ColladaModel.Load(String filename)
   at ColladaXna.Base.ColladaModel..ctor(String filename) ..."

So i tried to build WP7 version of this library, but also with no success - some parts of code is not supported on WP7 platform (eg. XmlNode type and so on).

So is there any way to use your awesome library on WP7 platform?

Thank you very much

Best Regards

Jakob

**Comment by Bunkerbewohner** [comment]
Hello Jakob!

I've never tested this library on WP7, but if you get that far it seems to be basically compatible. 
Your specific error rather looks like either an error in your DAE document or a bug / poor error handling in my code. Unfortunately I don't have the development environment etc. setup anymore, so I'm afraid you'll have to debug this yourself. 

If you don't need animation or joints, you could also disable the respective importers for the time being by removing the from the ColladaXna.Base.ColladaModel Load() method to circumvent the problem. But I'm not sure if that could cause other problems in the end.

**Comment by azzurit** [comment]
Hello, 

Thanks for swift replay!

I debugged it and find the source of the problem:
Model I tried to import, had no skeleton but also no joints. So I replaced SkeletonImporter.cs, method FindJointNodes, L158 like this:
list.Add(root);  -> if (root != null) { list.Add(root); }

Hope it helps to others;-)

Thanks again for your job

Best Regards
J

**Comment by Bunkerbewohner** [comment]
This problem was fixed in 8a0a6f8c. :-)
